{
 "title": "Wordpress",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nb utilisateurs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bitnami_wordpress",
     "rawSql": "SELECT COUNT(ID) FROM bitnami_wordpress.wp_users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Surveillance de l'utilisation CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"my-wordpress-56fb77bb48-7q927\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Surveillance de l'espace disque disponible dans les nœuds du cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{node=\"minikube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Surveillance de l'utilisation de la mémoire",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"my-wordpress-56fb77bb48-7q927\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Surveillance de la latence HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kubelet_http_requests_duration_seconds_bucket{le=\"0.1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Surveillance du trafic réseau entrant et sortant",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"minikube\"}[1m])) + sum(rate(container_network_transmit_bytes_total{instance=\"minikube\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}